name = "Botany"
author = "P1x3l101"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2c15230a7459e894750eb1747e3183de45d31fdda041813855fedd7254bdd7d"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
