name = "Botany"
author = "P1x3l101"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3af360aed23953c2535b7cf7a12ad9e5105e79947d1e10119c8175bf415ff75f"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
