#TLM: True POWER common settings
#Set the weight for Unawakened Soul finished products.
unawakened_soul_weight_list = [["true_power_of_maid:soul_of_combo_b", 1.0], ["true_power_of_maid:soul_of_combo_c", 1.0], ["true_power_of_maid:soul_of_rapid_slash", 1.0], ["true_power_of_maid:soul_of_air_combo", 1.0], ["true_power_of_maid:soul_of_mirage_blade", 1.0], ["true_power_of_maid:soul_of_trick", 1.0], ["true_power_of_maid:soul_of_judgement_cut", 1.0], ["true_power_of_maid:soul_of_just_judgement_cut", 1.0], ["true_power_of_maid:soul_of_void_slash", 1.0], ["true_power_of_maid:soul_of_guard", 1.0], ["true_power_of_maid:soul_of_health", 1.0], ["true_power_of_maid:soul_of_exp", 1.0], ["true_power_of_maid:soul_of_power", 0.5], ["true_power_of_maid:soul_of_true_power", 0.001]]
#Set max soul count of. (default: 10)
#Range: > 0
true_power_max_soul_count = 10

